services:
  - type: web
    name: rokto-dorkar-api
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py ensure_superuser
    startCommand: gunicorn Blood.wsgi:application --bind 0.0.0.0:$PORT
    healthCheckPath: /api/v1/health/
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_SSL
        value: "True"
      - key: ALLOWED_HOSTS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_SENDER_EMAIL
        sync: false
      - key: BREVO_SENDER_NAME
        value: Rokto Dorkar
