# Generated by Django 5.1.2 on 2026-09-24 21:18

from django.conf import settings
from django.db import migrations, models


def normalize_existing_phones(apps, schema_editor):
    Person = apps.get_model('Blood_app', 'Person')
    for person in Person.objects.exclude(mobile_number__isnull=True).iterator():
        digits = ''.join(character for character in person.mobile_number if character.isdigit())
        if digits.startswith('880'):
            digits = f'0{digits[3:]}'
        elif len(digits) == 10 and digits.startswith('1'):
            digits = f'0{digits}'
        if digits and digits != person.mobile_number:
            person.mobile_number = digits
            person.save(update_fields=('mobile_number',))


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_app', '0016_seed_demo_donors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(normalize_existing_phones, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='person',
            name='mobile_number',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['status', 'blood_group', '-created_at'], name='request_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='duplicatedonoralert',
            index=models.Index(fields=['status', '-created_at'], name='duplicate_status_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['blood_group'], name='donor_blood_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['division', 'district', 'subdistrict'], name='donor_location_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['is_available', 'lastdonate'], name='donor_eligible_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['-updated_at'], name='donor_updated_idx'),
        ),
    ]
